server:
  port: 7003
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/,http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true