server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/,http://localhost:8000/eureka/
spring:
  application:
    name: eureka-server
